### ISSUE TITLE
Need clarity on syntax for sheen-to-sheen routing

### ISSUE THREAD

**Issue by boriwo** [Comcast/sheens#21]
This is not really a sheen core question but I'll post it here anyways. With the introduction of the mcrew demo tool the syntax to send a message directly to a single sheen changed from `"to" : {"mid":"123"}` to `"to" : "123"`. This is not really a good fit with related work on the schema for message routing on a Kafka bus. There we need additional meta data (such as which topic to send the message to) which would make the previous syntax more suitable because it can be extended with additional meta data. Bottom line we should make sure that the syntax for message routing is consistent both locally and in the cloud and I'm afraid that currently it isn't.

**Comment by jsccast** [comment]
`mcrew` is a demo, and applications can supply their own routing behavior.

But it'd be nice to be able to have custom `mcrew` that's different mostly only in the routing.
