### ISSUE TITLE
New feature: Support inequalities in pattern variables

### ISSUE THREAD

**Issue by jsccast** [Comcast/sheens#28]
Today a guard can check an inequality. For example, the message `{"temp":10}` matched against `{"temp":"?t"}` results in a binding `{"?t":10}`, which a guard can contemplate based on (say) `t<12`.

The suggested new feature has two forms.

1. Support pattern variables of the form `"?<X"` and `"?>X"`. When given a binding for `?X`, one of those patterns matches if the respective inequality is true.

1. Support pattern variables of the form `"?<CONSTANT"` and `"?>CONSTANT"`, where `CONSTANT` is a constant literal (a number or string). A match would not extend the pattern matching bindings.

In both cases, also support `<=`, `>=`, and `!` (which means "not equal").

Since the above behavior can be accomplished with guards, this new behavior isn't necessary. However, possible gains in efficiency and conciseness seem to justify these special cases. (As an example, this feature would make dealing with out-of-order messages much easier.)

**Comment by jsccast** [comment]
A slippery slope?

**Comment by boriwo** [comment]
Feels a bit slippery.

**Comment by jsccast** [comment]
See comments at 3ed8fac.
