### ISSUE TITLE
Support optional pattern variables

### ISSUE THREAD

**Issue by westokyo** [Comcast/sheens#37]
There are numerous conditions where an incoming message might have an optional field. Currently the pattern matching algorithm requires every element in the pattern to be present in the incoming message. Thus in order to perform conditional matching multiple patterns must be generated.

As a user I would like for there to be a method by which I may tag a pattern element as _optional_.

Example:
pattern: `{ "e1": "v1", "??e2": "?v2", "e3": "?v3" }`

In this case `e2` would be _optional_.

Message: `{ "e1": "v1", "e2": "123", "e3": "456" }`
Would produce bindings of:
`{ "?v2": "123", "?v3": "456" }`

Message: `{ "e1": "v1", "e3": "456" }`
Would produce bindings of:
`{ "?v3": "456" }`

**Comment by jsccast** [comment]
The commit above implements something a bit different from the above. See the docs [here](https://github.com/Comcast/sheens/blob/master/core/match.md#49-optional-pattern-variable-absent) and [here](https://github.com/Comcast/sheens/blob/master/README.md#experimental-optional-pattern-variables) for more details.

Please re-open this issue if what's there now misses the mark.
