### ISSUE TITLE
Do we need this Find func?

### ISSUE THREAD

**Issue by kristinapathak** [Comcast/sheens#61]
https://github.com/Comcast/sheens/blob/6b3f6add2cb2519bd0819c65bf2c01106b91d111/core/actions.go#L94-L100

The `InterpretersMap` is a map to interfaces, whose empty value is `nil`.  Returning `m[name]` when `name` isn't in the map will return the empty value as well, so I don't think this function's logic works differently than `return m[name]`.

In a playground: https://play.golang.org/p/_F4bDZGFSej

**Comment by jsccast** [comment]
That `Find` is -- or at least was -- to make `InterpretersMap` an implementation of an `Interpreters`, which includes a `Find` method. `InterpretersMap` itself is really just an example of an `Interpreters`.

**Comment by kristinapathak** [comment]
Oh got it 👍
